version: '3.3'
services:
  db:
    image: mysql:latest
    container_name: technician_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE:  'techniciandb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: